### ISSUE TITLE
Auto Scroll don't work some times

### ISSUE THREAD

**Issue by pai4451** [Christopher-Hayes/vscode-chatgpt-reborn#14] opened 2023-03-25 15:13 UTC
### Describe the Bug

With the latest 3.11.2, I still find that the auto scroll to the bottom won't work in some cases.
https://github.com/gencay/vscode-chatgpt/issues/212

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

All the settings are left as default, but I found one setting `Stream Throttling` (default 100) which seems related to the UI performance. Is changing this value help the issue of auto-scroll failing to catch up with the streaming response?

### Additional context

As can see in the relative position of the scroll bar and the response in the following snapshot. The response still keeps generating but the scroll is not moving even after the generation finish.

<img width="610" alt="截圖 2023-03-25 下午11 06 10" src="https://user-images.githubusercontent.com/48813810/227725471-633937df-691c-4180-8c23-a47d8af3c6dd.png">

**Comment by LingCoder** [comment] 2023-03-26 02:00
same for me,please dont scrw up the extension, if you haven't thought about or tested the plugin. Because it is automatically updated by default in vscode, there are too many bugs in the past two days.

**Comment by Christopher-Hayes** [comment] 2023-03-26 03:39
Thank you for the bug report @pai4451. This behavior is actually partially intentional and in response to https://github.com/gencay/vscode-chatgpt/issues/212. Before the scroll would lock you out of being able to scroll. The code now scrolls **only** if you are scrolled to the bottom. It also allows you to scroll up while the code is generating, which was not feasible before. If you scroll back to the bottom, it re-locks onto the code as it is generating. What I can do here though is if you scroll up and then ask a new question, I can have to jump you down to the bottom.

In relation to `Stream throttling` - ideally scroll is not impacted by the value you set there. That's just streams the ai's text in either smaller or bigger chunks, which may improve UI performance if you pick a larger value.

**Comment by Christopher-Hayes** [comment] 2023-03-26 03:53
@LingCoder if you've experienced bugs, please [make a bug report](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/issues/new/choose).

Note that Gencay has [started a new extension, Genie AI,](https://github.com/gencay/vscode-chatgpt/issues/239#issuecomment-1476063915) so this extension is no longer just meant to keep the extension alive. If you don't like the newer changes I recommend trying [Genie AI](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode) out. But, I am open to feedback in [Discusions](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/discussions) if you're interested in contributing to this extension's roadmap.

**Comment by Christopher-Hayes** [comment] 2023-03-26 04:09
@pai4451 I've released `v3.11.4` which will now jump you down to the bottom when you ask a new question. I'm closing this issue as the rest of the behavior is functioning as intended, but if you find the autoscroll behavior doesn't work when you're scrolled to the bottom, LMK.

**Closed by Christopher-Hayes** 2023-03-26 04:09 UTC
Labels: bug
